name: Python and Selenium Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run unit tests for your Python code (app.py)
    - name: Run Python unit tests
      run: |
        python -m unittest discover

    # Install Chrome and ChromeDriver for Selenium
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver

    # Run Selenium tests (if you have any)
    - name: Run Selenium tests
      run: |
        python -m unittest discover -s tests/selenium_tests
